import { Category, Product, Size, Color, Coupon, Order, UserProfile } from "@/types";

export const MOCK_SIZES: Size[] = [
  { id: "sz-0-6m", name: "0-6 Months", displayOrder: 1 },
  { id: "sz-6-12m", name: "6-12 Months", displayOrder: 2 },
  { id: "sz-1-2y", name: "1-2 Years", displayOrder: 3 },
  { id: "sz-2-3y", name: "2-3 Years", displayOrder: 4 },
  { id: "sz-4-5y", name: "4-5 Years", displayOrder: 5 },
  { id: "sz-6-7y", name: "6-7 Years", displayOrder: 6 },
  { id: "sz-8-9y", name: "8-9 Years", displayOrder: 7 },
  { id: "sz-10-11y", name: "10-11 Years", displayOrder: 8 },
  { id: "sz-12-13y", name: "12-13 Years", displayOrder: 9 },
];

export const MOCK_COLORS: Color[] = [
  { id: "col-sky-blue", name: "Sky Blue", hexCode: "#38BDF8" },
  { id: "col-pastel-pink", name: "Pastel Pink", hexCode: "#F472B6" },
  { id: "col-crisp-white", name: "Crisp White", hexCode: "#FFFFFF" },
  { id: "col-navy-blue", name: "Navy Blue", hexCode: "#1E3A8A" },
  { id: "col-soft-sage", name: "Soft Sage", hexCode: "#10B981" },
  { id: "col-sunny-amber", name: "Sunny Amber", hexCode: "#F59E0B" },
  { id: "col-coral-rose", name: "Coral Rose", hexCode: "#E05A47" },
  { id: "col-heather-grey", name: "Heather Grey", hexCode: "#6B7280" },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-boys",
    name: "Boys Collection",
    slug: "boys",
    description: "Durable, stylish and comfortable outfits tailored for adventurous boys.",
    imageUrl: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=800&auto=format&fit=crop",
    displayOrder: 1,
    isActive: true,
    productCount: 8,
  },
  {
    id: "cat-girls",
    name: "Girls Collection",
    slug: "girls",
    description: "Delightful dresses, skirts, and chic casual wear for every little girl's dream wardrobe.",
    imageUrl: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?q=80&w=800&auto=format&fit=crop",
    displayOrder: 2,
    isActive: true,
    productCount: 7,
  },
  {
    id: "cat-baby",
    name: "Baby & Toddlers",
    slug: "baby-toddlers",
    description: "Ultra-gentle 100% organic cotton rompers, onesies, and sets for delicate baby skin.",
    imageUrl: "https://images.unsplash.com/photo-1522771930-78848d9293e8?q=80&w=800&auto=format&fit=crop",
    displayOrder: 3,
    isActive: true,
    productCount: 5,
  },
  {
    id: "cat-tshirts",
    name: "T-Shirts & Tops",
    slug: "t-shirts-tops",
    description: "Breathable daily-wear cotton graphic tees, polos, and henleys.",
    imageUrl: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=800&auto=format&fit=crop",
    displayOrder: 4,
    isActive: true,
    productCount: 6,
  },
  {
    id: "cat-dresses",
    name: "Dresses & Frocks",
    slug: "dresses-frocks",
    description: "Twirl-worthy party dresses, floral summer frocks, and festive wear.",
    imageUrl: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=800&auto=format&fit=crop",
    displayOrder: 5,
    isActive: true,
    productCount: 4,
  },
  {
    id: "cat-hoodies",
    name: "Hoodies & Jackets",
    slug: "hoodies-jackets",
    description: "Cozy fleece pullovers, windbreakers, and light jackets for active outdoor fun.",
    imageUrl: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=800&auto=format&fit=crop",
    displayOrder: 6,
    isActive: true,
    productCount: 4,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Little Explorer Organic Cotton Tee",
    slug: "little-explorer-cotton-tee",
    description: "Crafted from 100% combed organic cotton, this breathable tee keeps your active child cool and comfy all day. Features reinforced neck stitching and non-toxic water-based screen printing.",
    fabricMaterial: "100% Combed Organic Cotton (180 GSM)",
    careInstructions: "Machine wash cold with like colors. Tumble dry low. Do not iron print.",
    gender: "BOYS",
    ageGroup: "4-5Y",
    basePrice: 1850,
    salePrice: 1450,
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    categoryId: "cat-boys",
    ratingAverage: 4.8,
    reviewCount: 24,
    images: [
      {
        id: "img-1a",
        productId: "prod-1",
        imageUrl: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=800&auto=format&fit=crop",
        altText: "Little Explorer Organic Cotton Tee front view",
        isPrimary: true,
        displayOrder: 1,
      },
      {
        id: "img-1b",
        productId: "prod-1",
        imageUrl: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=800&auto=format&fit=crop",
        altText: "Little Explorer Cotton Tee lifestyle detail",
        isPrimary: false,
        displayOrder: 2,
      },
    ],
    variants: [
      {
        id: "var-1a",
        productId: "prod-1",
        sizeId: "sz-2-3y",
        colorId: "col-sky-blue",
        sku: "GS-TEE-BLU-23",
        stockQuantity: 12,
        size: MOCK_SIZES[3],
        color: MOCK_COLORS[0],
      },
      {
        id: "var-1b",
        productId: "prod-1",
        sizeId: "sz-4-5y",
        colorId: "col-sky-blue",
        sku: "GS-TEE-BLU-45",
        stockQuantity: 8,
        size: MOCK_SIZES[4],
        color: MOCK_COLORS[0],
      },
      {
        id: "var-1c",
        productId: "prod-1",
        sizeId: "sz-6-7y",
        colorId: "col-crisp-white",
        sku: "GS-TEE-WHT-67",
        stockQuantity: 15,
        size: MOCK_SIZES[5],
        color: MOCK_COLORS[2],
      },
      {
        id: "var-1d",
        productId: "prod-1",
        sizeId: "sz-8-9y",
        colorId: "col-navy-blue",
        sku: "GS-TEE-NVY-89",
        stockQuantity: 0, // Intentionally out of stock demo
        size: MOCK_SIZES[6],
        color: MOCK_COLORS[3],
      },
    ],
  },
  {
    id: "prod-2",
    name: "Floral Meadow Ruffle Summer Dress",
    slug: "floral-meadow-ruffle-dress",
    description: "A breezy, pastel-hued floral frock featuring flutter butterfly sleeves and a tiered gathered skirt. Lined with ultra-soft cotton voile to prevent itching during summer play.",
    fabricMaterial: "100% Breathable Cotton Poplin with Voile Lining",
    careInstructions: "Delicate machine wash. Line dry in shade. Warm iron if needed.",
    gender: "GIRLS",
    ageGroup: "6-7Y",
    basePrice: 3200,
    salePrice: 2650,
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    categoryId: "cat-girls",
    ratingAverage: 4.9,
    reviewCount: 38,
    images: [
      {
        id: "img-2a",
        productId: "prod-2",
        imageUrl: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?q=80&w=800&auto=format&fit=crop",
        altText: "Floral Meadow Ruffle Summer Dress full presentation",
        isPrimary: true,
        displayOrder: 1,
      },
      {
        id: "img-2b",
        productId: "prod-2",
        imageUrl: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?q=80&w=800&auto=format&fit=crop",
        altText: "Dress fabric texture and delicate floral patterns",
        isPrimary: false,
        displayOrder: 2,
      },
    ],
    variants: [
      {
        id: "var-2a",
        productId: "prod-2",
        sizeId: "sz-4-5y",
        colorId: "col-pastel-pink",
        sku: "GS-DRS-PNK-45",
        stockQuantity: 6,
        size: MOCK_SIZES[4],
        color: MOCK_COLORS[1],
      },
      {
        id: "var-2b",
        productId: "prod-2",
        sizeId: "sz-6-7y",
        colorId: "col-pastel-pink",
        sku: "GS-DRS-PNK-67",
        stockQuantity: 9,
        size: MOCK_SIZES[5],
        color: MOCK_COLORS[1],
      },
      {
        id: "var-2c",
        productId: "prod-2",
        sizeId: "sz-8-9y",
        colorId: "col-coral-rose",
        sku: "GS-DRS-CRL-89",
        stockQuantity: 4,
        size: MOCK_SIZES[6],
        color: MOCK_COLORS[6],
      },
    ],
  },
  {
    id: "prod-3",
    name: "Snuggle Cloud Organic Baby Romper",
    slug: "snuggle-cloud-baby-romper",
    description: "Designed for effortless diaper changes with nickel-free snaps along the inseam and envelope neck shoulders. Ultra-stretchy ribbed organic cotton guarantees baby's tummy stays comfy.",
    fabricMaterial: "95% GOTS Certified Organic Cotton, 5% Elastane",
    careInstructions: "Machine wash warm with baby-safe detergent. Tumble dry medium.",
    gender: "BABY",
    ageGroup: "6-12M",
    basePrice: 1950,
    salePrice: 1550,
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    categoryId: "cat-baby",
    ratingAverage: 5.0,
    reviewCount: 42,
    images: [
      {
        id: "img-3a",
        productId: "prod-3",
        imageUrl: "https://images.unsplash.com/photo-1522771930-78848d9293e8?q=80&w=800&auto=format&fit=crop",
        altText: "Snuggle Cloud Organic Baby Romper in soft sage",
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    variants: [
      {
        id: "var-3a",
        productId: "prod-3",
        sizeId: "sz-0-6m",
        colorId: "col-soft-sage",
        sku: "GS-RMP-SGE-06",
        stockQuantity: 14,
        size: MOCK_SIZES[0],
        color: MOCK_COLORS[4],
      },
      {
        id: "var-3b",
        productId: "prod-3",
        sizeId: "sz-6-12m",
        colorId: "col-soft-sage",
        sku: "GS-RMP-SGE-612",
        stockQuantity: 11,
        size: MOCK_SIZES[1],
        color: MOCK_COLORS[4],
      },
      {
        id: "var-3c",
        productId: "prod-3",
        sizeId: "sz-1-2y",
        colorId: "col-sunny-amber",
        sku: "GS-RMP-AMB-12",
        stockQuantity: 7,
        size: MOCK_SIZES[2],
        color: MOCK_COLORS[5],
      },
    ],
  },
  {
    id: "prod-4",
    name: "Adventure Fleece Zip-Up Hoodie",
    slug: "adventure-fleece-zip-hoodie",
    description: "Heavyweight brushed fleece hoodie with a kangaroo pocket, sturdy YKK safety zipper, and double-layered hood. Perfect for crisp morning walks and playground adventures.",
    fabricMaterial: "80% Cotton, 20% Polyester Heavyweight Fleece",
    careInstructions: "Machine wash cold inside out. Tumble dry gentle. Do not bleach.",
    gender: "UNISEX",
    ageGroup: "8-9Y",
    basePrice: 3450,
    salePrice: 2890,
    isFeatured: true,
    isNewArrival: true,
    isActive: true,
    categoryId: "cat-hoodies",
    ratingAverage: 4.7,
    reviewCount: 19,
    images: [
      {
        id: "img-4a",
        productId: "prod-4",
        imageUrl: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=800&auto=format&fit=crop",
        altText: "Adventure Fleece Zip-Up Hoodie in Heather Grey",
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    variants: [
      {
        id: "var-4a",
        productId: "prod-4",
        sizeId: "sz-6-7y",
        colorId: "col-heather-grey",
        sku: "GS-HOD-GRY-67",
        stockQuantity: 5,
        size: MOCK_SIZES[5],
        color: MOCK_COLORS[7],
      },
      {
        id: "var-4b",
        productId: "prod-4",
        sizeId: "sz-8-9y",
        colorId: "col-navy-blue",
        sku: "GS-HOD-NVY-89",
        stockQuantity: 8,
        size: MOCK_SIZES[6],
        color: MOCK_COLORS[3],
      },
      {
        id: "var-4c",
        productId: "prod-4",
        sizeId: "sz-10-11y",
        colorId: "col-heather-grey",
        sku: "GS-HOD-GRY-1011",
        stockQuantity: 3,
        size: MOCK_SIZES[7],
        color: MOCK_COLORS[7],
      },
    ],
  },
  {
    id: "prod-5",
    name: "Everyday Stretch Play Denim Jeans",
    slug: "everyday-stretch-play-denim",
    description: "Built for active kids who climb, run, and jump. Features an adjustable interior buttonhole waistband that grows with your child, reinforced knee panels, and 4-way stretch denim.",
    fabricMaterial: "98% Cotton Denim, 2% Spandex Elastic Weave",
    careInstructions: "Wash inside out with dark colors. Tumble dry medium.",
    gender: "BOYS",
    ageGroup: "6-7Y",
    basePrice: 2850,
    salePrice: 2350,
    isFeatured: false,
    isNewArrival: true,
    isActive: true,
    categoryId: "cat-boys",
    ratingAverage: 4.6,
    reviewCount: 15,
    images: [
      {
        id: "img-5a",
        productId: "prod-5",
        imageUrl: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?q=80&w=800&auto=format&fit=crop",
        altText: "Everyday Stretch Play Denim Jeans",
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    variants: [
      {
        id: "var-5a",
        productId: "prod-5",
        sizeId: "sz-4-5y",
        colorId: "col-navy-blue",
        sku: "GS-JNS-NVY-45",
        stockQuantity: 10,
        size: MOCK_SIZES[4],
        color: MOCK_COLORS[3],
      },
      {
        id: "var-5b",
        productId: "prod-5",
        sizeId: "sz-6-7y",
        colorId: "col-navy-blue",
        sku: "GS-JNS-NVY-67",
        stockQuantity: 12,
        size: MOCK_SIZES[5],
        color: MOCK_COLORS[3],
      },
      {
        id: "var-5c",
        productId: "prod-5",
        sizeId: "sz-8-9y",
        colorId: "col-navy-blue",
        sku: "GS-JNS-NVY-89",
        stockQuantity: 6,
        size: MOCK_SIZES[6],
        color: MOCK_COLORS[3],
      },
    ],
  },
  {
    id: "prod-6",
    name: "Pastel Button-Down Linen Casual Shirt",
    slug: "pastel-button-down-linen-shirt",
    description: "Smart-casual summer shirt cut from premium linen-cotton blend. Roll-up sleeve tabs and button collar make this ideal for Eid, family weddings, or weekend brunches.",
    fabricMaterial: "55% Natural Linen, 45% Cotton",
    careInstructions: "Machine wash cold gentle cycle. Warm iron while slightly damp.",
    gender: "BOYS",
    ageGroup: "4-5Y",
    basePrice: 2400,
    salePrice: 1950,
    isFeatured: true,
    isNewArrival: false,
    isActive: true,
    categoryId: "cat-boys",
    ratingAverage: 4.8,
    reviewCount: 22,
    images: [
      {
        id: "img-6a",
        productId: "prod-6",
        imageUrl: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=800&auto=format&fit=crop",
        altText: "Pastel Button-Down Linen Casual Shirt in Sky Blue",
        isPrimary: true,
        displayOrder: 1,
      },
    ],
    variants: [
      {
        id: "var-6a",
        productId: "prod-6",
        sizeId: "sz-2-3y",
        colorId: "col-sky-blue",
        sku: "GS-SHT-BLU-23",
        stockQuantity: 5,
        size: MOCK_SIZES[3],
        color: MOCK_COLORS[0],
      },
      {
        id: "var-6b",
        productId: "prod-6",
        sizeId: "sz-4-5y",
        colorId: "col-crisp-white",
        sku: "GS-SHT-WHT-45",
        stockQuantity: 8,
        size: MOCK_SIZES[4],
        color: MOCK_COLORS[2],
      },
    ],
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: "coup-welcome",
    code: "WELCOME10",
    discountType: "PERCENTAGE",
    discountValue: 10,
    minOrderAmount: 2000,
    maxDiscountAmount: 1000,
    usageLimit: 500,
    timesUsed: 62,
    startDate: "2026-01-01T00:00:00Z",
    expiryDate: "2026-12-31T23:59:59Z",
    isActive: true,
  },
  {
    id: "coup-flat500",
    code: "KIDSFEST500",
    discountType: "FIXED",
    discountValue: 500,
    minOrderAmount: 4000,
    maxDiscountAmount: 500,
    usageLimit: 200,
    timesUsed: 41,
    startDate: "2026-03-01T00:00:00Z",
    expiryDate: "2026-11-30T23:59:59Z",
    isActive: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-1001",
    orderNumber: "GS-2026-8901",
    userId: "usr-demo-1",
    status: "DELIVERED",
    paymentMethod: "COD",
    paymentStatus: "PAID",
    subtotal: 4100,
    discountAmount: 410,
    shippingFee: 0,
    totalAmount: 3690,
    couponCode: "WELCOME10",
    shippingAddress: {
      recipientName: "Ayesha Malik",
      phone: "+92 300 1234567",
      streetAddress: "House 42-B, Street 14, Phase 5, DHA",
      city: "Lahore",
      province: "Punjab",
      postalCode: "54792",
      country: "Pakistan",
    },
    items: [
      {
        id: "item-1",
        orderId: "ord-1001",
        productId: "prod-1",
        productName: "Little Explorer Organic Cotton Tee",
        productSlug: "little-explorer-cotton-tee",
        productImage: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?q=80&w=800&auto=format&fit=crop",
        sizeName: "4-5 Years",
        colorName: "Sky Blue",
        unitPrice: 1450,
        quantity: 1,
        lineTotal: 1450,
      },
      {
        id: "item-2",
        orderId: "ord-1001",
        productId: "prod-2",
        productName: "Floral Meadow Ruffle Summer Dress",
        productSlug: "floral-meadow-ruffle-dress",
        productImage: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?q=80&w=800&auto=format&fit=crop",
        sizeName: "6-7 Years",
        colorName: "Pastel Pink",
        unitPrice: 2650,
        quantity: 1,
        lineTotal: 2650,
      },
    ],
    createdAt: "2026-10-01T14:32:00Z",
    updatedAt: "2026-10-04T11:15:00Z",
  },
  {
    id: "ord-1002",
    orderNumber: "GS-2026-8902",
    userId: "usr-demo-2",
    status: "PROCESSING",
    paymentMethod: "COD",
    paymentStatus: "PENDING",
    subtotal: 2890,
    discountAmount: 0,
    shippingFee: 250,
    totalAmount: 3140,
    shippingAddress: {
      recipientName: "Hamza Tariq",
      phone: "+92 321 7654321",
      streetAddress: "Apartment 304, Creek Vistas, Clifton",
      city: "Karachi",
      province: "Sindh",
      postalCode: "75600",
      country: "Pakistan",
    },
    items: [
      {
        id: "item-3",
        orderId: "ord-1002",
        productId: "prod-4",
        productName: "Adventure Fleece Zip-Up Hoodie",
        productSlug: "adventure-fleece-zip-hoodie",
        productImage: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?q=80&w=800&auto=format&fit=crop",
        sizeName: "8-9 Years",
        colorName: "Navy Blue",
        unitPrice: 2890,
        quantity: 1,
        lineTotal: 2890,
      },
    ],
    createdAt: "2026-10-04T19:20:00Z",
    updatedAt: "2026-10-05T09:45:00Z",
  },
];

export const MOCK_USERS: UserProfile[] = [
  {
    id: "usr-admin-1",
    email: "admin@gscollection.pk",
    fullName: "Gullu Shani Admin",
    phone: "+92 300 8888999",
    role: "ADMIN",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "usr-demo-1",
    email: "ayesha.malik@example.com",
    fullName: "Ayesha Malik",
    phone: "+92 300 1234567",
    role: "CUSTOMER",
    addresses: [
      {
        id: "addr-ayesha-1",
        recipientName: "Ayesha Malik",
        phone: "+92 300 1234567",
        streetAddress: "House 42-B, Street 14, Phase 5, DHA",
        city: "Lahore",
        province: "Punjab",
        postalCode: "54792",
        country: "Pakistan",
        isDefault: true,
      },
    ],
    createdAt: "2026-08-15T10:11:00Z",
  },
];
